replace git_clone implementation with gitsick-bootstrap implementation

diff --git a/gitsick b/gitsick
--- a/gitsick
+++ b/gitsick
@@ -48,7 +48,7 @@ main() {
             local NAME="$1"
             shift
             init_git_dir "$NAME"
-            git_clone "$@"
+            git_clone "$1"
             exit $?
             ;;
     esac
@@ -112,18 +112,30 @@ git_init() {
 }
 
 git_clone() {
-    local CLONE_DIR
-    OS="$(uname -s)"
-    case "$OS" in
-        Linux) CLONE_DIR="$(mktemp --tmpdir --directory $GITSICK.XXX)" ;;
-        Darwin) CLONE_DIR="$(mktemp -d -t $GITSICK)" ;;
-        *) die "ERROR: Unknown OS: $OS" ;;
-    esac
-    git clone --no-checkout --separate-git-dir "$GIT_DIR" "$@" "$CLONE_DIR"
-    git config --file "$GIT_DIR"/config core.worktree $GIT_WORK_TREE
-    rm "$CLONE_DIR"/.git
-    rmdir "$CLONE_DIR"
-    git_cmd checkout
+    local HTTPS_URL="$1"
+
+    if ! test -d "$GIT_DIR"
+    then
+        git clone --bare "$HTTPS_URL" "$GIT_DIR"
+    fi
+
+    (
+        git --work-tree "$GIT_WORK_TREE" --git-dir "$GIT_DIR" reset --mixed master > /dev/null
+        git --work-tree "$GIT_WORK_TREE" --git-dir "$GIT_DIR" ls-files --modified -z | while read -d $'\0' -r FILE
+        do
+            FILE="$GIT_WORK_TREE/$FILE"
+            if test -f "$FILE"
+            then
+                if test -f "$FILE.bak"
+                then
+                    echo "$0: cannot backup file: $File"
+                    exit 1
+                fi
+                mv --verbose --no-clobber "$FILE" "$FILE.bak"
+            fi
+        done
+        git --work-tree "$GIT_WORK_TREE" --git-dir "$GIT_DIR" reset --hard master > /dev/null
+    )
 }
 
 git_cmd() {
